name: team_10_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.9
  dots_indicator: ^3.0.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/image/
    - assets/


  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/ProtestStrike-Regular.ttf

    - family: Open
      fonts:
        - asset: assets/fonts/OpenSans.ttf

    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
